SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_VERSION 1)
SET(CMAKE_SYSTEM_PROCESSOR armhf)

SET(CMAKE_C_COMPILER   /usr/bin/arm-linux-gnueabihf-gcc)
SET(CMAKE_CXX_COMPILER   /usr/bin/arm-linux-gnueabihf-g++)
SET(CMAKE_C_LIBRARY_ARCHITECTURE arm-linux-gnueabihf)
SET(CMAKE_CXX_LIBRARY_ARCHITECTURE arm-linux-gnueabihf)
SET(CMAKE_LIBRARY_ARCHITECTURE arm-linux-gnueabihf)

SET(CMAKE_SYSROOT /mnt/pi)
SET(CMAKE_FIND_ROOT_PATH  /mnt/pi)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
